sudo: true
language: node_js
node_js:
  - 8 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - dev # build master branch only
# 下载主题
# before_install:
#   - git clone https://github.com/theme-next/hexo-theme-next themes/next
install:
  - npm install
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: dev
  local-dir: public
  target_branch: master